[project]
name = "streamlit-app"
version = "0.0.1"
requires-python = ">=3.13,<4.0"
dependencies = [
  "streamlit>=1.41.1,<2.0.0",
  "watchdog>=6.0.0,<7.0.0",
  "aws-lambda-powertools[tracer]>=3.4.1,<4.0.0",
]

[dependency-groups]
dev = [
  "ruff>=0.16.7,<0.17.0",
  "pyright>=1.1.379,<1.2.0",
  "types-cachetools>=6.0.0,<8.0.0",
  "types-decorator>=5.1.8,<6.0.0",
  "types-jsonschema>=4.23.0,<5.0.0",
  "types-protobuf>=6.30.2,<7.0.0",
  "types-pycurl>=7.45.4,<8.0.0",
  "types-toml>=0.10.8,<0.11.0",
]

[tool.uv.build-backend]
source-include = ["src/**", "pyproject.toml", "README.md"]
source-exclude = ["tests/**"]

[tool.ruff]
line-length = 88
exclude = ["build", ".venv", "envs", ".github/copilot-instructions.md"]
preview = true

[tool.ruff.lint]
select = ["ALL"]
ignore = [
  "missing-type-function-argument",
  "missing-type-args",
  "missing-type-kwargs",
  "missing-return-type-undocumented-public-function",
  "missing-return-type-private-function",
  "missing-return-type-special-method",
  "missing-return-type-static-method",
  "missing-return-type-class-method",
  "any-type",
  "boolean-type-hint-positional-argument",
  "boolean-default-value-positional-argument",
  "boolean-positional-value-in-call",
  "missing-copyright-notice",
  "shebang-not-executable",
  "shebang-missing-executable-file",
  "shebang-missing-python",
  "shebang-leading-whitespace",
  "future-rewritable-type-annotation",
  "future-required-type-annotation",
  "unnecessary-return-none",
  "implicit-return-value",
  "implicit-return",
  "unnecessary-assign",
  "superfluous-else-return",
  "superfluous-else-raise",
  "superfluous-else-continue",
  "superfluous-else-break",
  "missing-trailing-comma",
  "single-line-implicit-string-concatenation",
  "unnecessary-placeholder",
  "raise-vanilla-args",
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.pyright]
typeCheckingMode = "strict"
exclude = ["build", ".venv", "envs"]
venvPath = "."
venv = ".venv"
threads = 0
reportUnknownMemberType = false
reportUnknownVariableType = false
reportUnknownArgumentType = false

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = []
only-include = ["pyproject.toml", "src/**", "README.md"]

[tool.hatch.build.targets.sdist]
only-include = ["pyproject.toml", "src/**", "README.md"]
